### ISSUE TITLE
Add ability to check if touch is pending by external process

### ISSUE THREAD

**Issue by invidian** [maximbaz/yubikey-touch-detector#23]
To allow easier integration with other plugin systems, for example with https://docs.xfce.org/panel-plugins/xfce4-genmon-plugin, it would be nice if one could for example send a command to UNIX socket to get the current state and act accordingly. That would allow polling periodically for state, which is simpler than having a continuously running process.

With https://docs.xfce.org/panel-plugins/xfce4-genmon-plugin example, the difference is writing your Panel Plugin in C vs making a bash command echoing specific icon conditionally, which is a big difference.

**Comment by maximbaz** [comment]
Hello! I completely understand the point in making it simple to integrate with other panels, so let us try to find a solution.

The app is designed for pushing the updates, rather than polling for state, because (1) in 99% of the time yubikey is _not_ waiting for a touch, such polling would be a waste of resources, (2) it lets me keep the code simple and stateless as different touch reasons are detected in different way and don't need to know about each other / deal with race conditions. A proposed idea with bi-directional communication over the socket might not work because there might be multiple listeners, who would suddenly be confused of the unexpected new or repeated messages.

If `xfce4-genmon-plugin` does not support refreshing a module on demand, I would suggest creating a simple script that would take care of keeping the state, a quick idea is below, it's based on my [script for waybar](https://github.com/maximbaz/dotfiles/blob/master/.local/bin/waybar-yubikey), but simplified for example to not deal with different touch reasons:

```bash
#!/bin/bash

socket="${XDG_RUNTIME_DIR:-/run/user/$UID}/yubikey-touch-detector.socket"
marker="$HOME/.cache/touch-marker"

while true; do
    touch_requests=0

    if [ ! -e "$socket" ]; then
        while [ ! -e "$socket" ]; do sleep 1; done
    fi

    nc -U "$socket" | while read -n5 cmd; do
        if [ "${cmd:4:1}" = "1" ]; then
            ((touch_requests++))
        else
            ((touch_requests--))
        fi

        if (( touch_requests )); then
            echo 1 > "$marker"
        else
            echo 0 > "$marker"
        fi
    done

    sleep 1
done
```

Then your polling script could simply poll the `$marker` file.

Let me know if helps and what you think 🙂

**Comment by invidian** [comment]
Thanks for creative reply @maximbaz! I clearly didn't think this trough enough :smile: I looked how other plugins are implemented, but I didn't come up that I can run one more process as a daemon to write the state to file :facepalm: Now that you mention it, it seems so obvious :smile: :pray: 

I'll give a try the script you posted, I'm pretty sure it will work just fine. Feel free to close this issue. When I find some time to implement it, I will post an update here.

**Comment by maximbaz** [comment]
Awesome! Feel free to also add it to the bottom of README if you want 🙂

**Comment by invidian** [comment]
>Awesome! Feel free to also add it to the bottom of README if you want slightly_smiling_face

Created #24 then :)
