### ISSUE TITLE
Optional notification icon

### ISSUE THREAD

**Issue by twouters** [maximbaz/yubikey-touch-detector#25]
Would it be possible to add an optional icon to libnotify notifications to make it stand out a bit?

Could be based on [touch.svg from yubioath-desktop](https://github.com/Yubico/yubioath-desktop/blob/94edf799b6df3bf20d9dbfa76470628f3aae8946/images/touch.svg) if it's allowed to use their images.

**Comment by maximbaz** [comment]
I'm a little hesitant because the libnotify was added more like an example than a full-blown feature, my intention was to keep this project as a backend process and let people build any frontend they want on top. So if we start adding abilities to configure icons, we will open the door for configurable text and title in notification, then template support, then grouping notifications by type, etc...

Might I suggest trying out the API to build your own notification on top? In a simplest form, it's a script like so:

```sh
nc -U /run/user/1000/yubikey-touch-detector.socket | while read -n5 cmd; do
    if [ "${cmd:4:1}" = "1" ]; then
        # YubiKey is waiting for a touch! Call notify-send, play sound, change wallpaper, etc...
    fi
done
```

But I would suggest taking [my waybar module](https://github.com/maximbaz/dotfiles/blob/master/.local/bin/waybar-yubikey) as a starting point and then replace `printf` calls with a notification.

**Comment by twouters** [comment]
Alright, that makes perfect sense.

**Comment by twouters** [comment]
In case somebody every passes by: I've worked around this by overriding the icon path in `dunstrc` — I'm using [dunst](https://github.com/dunst-project/dunst) as a notification daemon.

```
[yubikey-touch-detector]
    appname = "yubikey-touch-detector"
    new_icon = <path-to-icon>
```

**Comment by jirutka** [comment]
The only change needed to support notification icon is this:

```diff
--- notifier/libnotify.go.orig
+++ notifier/libnotify.go
@@ -33,6 +33,7 @@
 
 	notification := notify.Notification{
 		AppName: "yubikey-touch-detector",
+		AppIcon: "yubikey-touch-detector",
 		Summary: "YubiKey is waiting for a touch",
 	}
 ```

You don’t have to provide the actual icon. If the notification service doesn’t find any, it just doesn’t display any icon (i.e. the current behaviour). This one-line change will allow the users to add their own icon named `yubikey-touch-detector.[ext]` to one of the standard icon directories.

**Comment by maximbaz** [comment]
I like this compromise 🙂  Applied in https://github.com/maximbaz/yubikey-touch-detector/commit/916faea86ca3932ae096a7f03ec86f6a1845394a

**Comment by AndrewKvalheim** [comment]
Added via #46
