### ISSUE TITLE
[feature request] add an option for custom notification message.

### ISSUE THREAD

**Issue by ftpd** [maximbaz/yubikey-touch-detector#34]
I mean, `YubiKey is waiting for a touch` is fine, but it would be nice if it could be customizable. Me, for example, this weird 'minimalist', thinks the current message is too long and takes a lot of screen's real estate ;-)

**Comment by maximbaz** [comment]
To be entirely honest I never liked having libnotify integration built-in in the first place (and treated "specially" comparing to all other GUI integrations), precisely because with all the titles, messages and icons you can end up maintaining more configuration options for libnotify than for the rest of the app... 😅

Especially because it's super easy to hook into the app (using socket ([many examples here](https://github.com/maximbaz/yubikey-touch-detector/wiki)), or the more recent [stdout](https://github.com/maximbaz/yubikey-touch-detector/pull/32)) and provide completely custom kind of GUI indication. 

It was a very popular request to have libnotify built-in, something that _just works_ out of the box, everywhere, and requires no configs, that made me add it... But you can probably sense I'm a bit hesitant to make it more flashy than it already is. 😁 

----

As a minimalist to a minimalist, wouldn't you want to add a Yubikey indicator to your bar in qtile, like is shown on the demo gif in the README? Wiki has a lot of examples of how this can be done, and I can also help you out if you get stuck (if you promise to document it on wiki to help other fellow users of qtile 😜 ).

**Comment by ftpd** [comment]
I already [have it in my bar](https://i.imgur.com/aPRLjWV.png). I just wanted to modify the message without modifying the code/building it from sources locally. That's what github binary releases are for, especially for go ;-)

An hour ago I was using `--stdout` in a helper script (and my qtile had the item in statusbar which invoked the other helper, to show the actual message) - it's all removed in [this commit](https://git.insomniac.pl/ftpd/dotfiles/commit/00a2734c8474190de36ce4941d323b00b53570a8). Now, when qtile can handle notifications properly, I want to get rid of silly helpers - which I did in this commit.

I fully understand you don't want to add blows&whistles when you don't feel they are needed. Sure, I will live with 'long' message or clone, edit and build it locally in the future, maybe ;-)

If you're 100% sure you don't want to add it, please close the issue. No hard feeling, I promise.

**Comment by maximbaz** [comment]
Wow, a bar getting content from libnotify is definitely a new idea to me, interesting! What if you add `fmt: "touch the yubikey"` to the config of your `Notify` widget?

**Comment by ftpd** [comment]
`fmt` works, but it obviously breaks all other notifications ;-)

`parse_text` looks like something worth checking. I will do it (tomorrow, it's 1:39 am in my timezone) and let you know.

**Comment by ftpd** [comment]
<closing as 'no longer relevant'>

**Comment by maximbaz** [comment]
Happy we could solve your use-case! Maybe you could add a snippet of your config to the wiki, since it's an interesting and perhaps unique feature of qtile to be able to modify notification text? And in any case, enjoy the app 😉

**Comment by maximbaz** [comment]
Ah, perfect, thanks 👍
