### ISSUE TITLE
Missing GPG pubring causes error

### ISSUE THREAD

**Issue by mlofjard** [maximbaz/yubikey-touch-detector#38]
I have no PGP keys configured on my Yubikey. Thus I get an error message about missing files everytime I run the program. Maybe you could add a flag to the config for disabling the GnuPG pubring file watch?

**Comment by maximbaz** [comment]
Oh this is interesting use-case! Do you get an error that `$HOME/.gnupg/pubring.kbx` does not exist? I think in that case we can simply use this fact alone, without introducing any flags, so that the apps works for you out of the box.

Would you like to try submitting a PR?

This is the variable containing the pubring path:

https://github.com/maximbaz/yubikey-touch-detector/blob/a2161c415e609bf4576f67b491bad0be9ee6f875/main.go#L61

And this is the block that initializes different watch methods:

https://github.com/maximbaz/yubikey-touch-detector/blob/a2161c415e609bf4576f67b491bad0be9ee6f875/main.go#L81-L87

I would suggest moving `WatchU2F` and `WatchHMAC` on top (e.g. above line 81), and the remaining block would be all about `gpg`. Then just wrap it in a condition, checking whether `gpgPubringPath` exists, and see if it works with your Yubikey.

If you don't have the capacity to do it, no worries, I'll get to it at some point :slightly_smiling_face:

**Comment by mlofjard** [comment]
Sure, I'll give it a go (pun intended). :) #39

**Comment by maximbaz** [comment]
Woohoo, thanks for testing this idea and making a PR! I'll merge and make a release tonight.

**Comment by maximbaz** [comment]
0.10.1 released, thanks!
